services:
  soloproxy:
    image: ghcr.io/walofz/go-solopool/solo-proxy:latest
    container_name: solo-proxy
    restart: unless-stopped
    network_mode: "host"
    environment:
      - TZ=Asia/Bangkok
      - RPC_URL=http://127.0.0.1:13031
      - RPC_USER=your_rpc_username
      - RPC_PASS=your_rpc_password
      - ZMQ_URL=tcp://127.0.0.1:28332
      - STRATUM_PORT=:3333
      - WEB_PORT=:8080
      - FIXED_DIFF=10000
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/YOUR_WEBHOOK_ID/YOUR_WEBHOOK_TOKEN
      - WALLET_ADDRESS=wallet_legacy_here
